/**
 * This file is part of groufix.
 * Copyright (c) Stef Velzel. All rights reserved.
 *
 * groufix : graphics engine produced by Stef Velzel.
 * www     : <www.vuzzel.nl>
 */

#include "groufix/core/mem.h"
#include <stdlib.h>
#include <string.h>


// 'Randomized' magic number (generated by human imagination).
#define GFX_HEADER_MAGIC_ ((uint32_t)0xff60af14)


// Pushes an lvalue to a hash key being built.
#define GFX_KEY_PUSH_(value) \
	do { \
		if (gfx_hash_builder_push_( \
			&builder, sizeof(value), &(value)) == NULL) \
		{ \
			goto clean; \
		} \
	} while (0)

// Pushes a handle into a hash key being built.
#define GFX_KEY_PUSH_HANDLE_() \
	do { \
		if (gfx_hash_builder_push_( \
			&builder, sizeof(*handles), &handles[currHandle++]) == NULL) \
		{ \
			goto clean; \
		} \
	} while (0)


/****************************
 * Unpacked groufix pipeline cache header.
 */
typedef struct GFXPipelineCacheHeader_
{
	uint32_t magic; // Equal to GFX_HEADER_MAGIC_.

	// Data size & hash including this header (with hash set to 0).
	uint32_t dataSize;
	uint64_t dataHash;

	// Vulkan values to validate compatibility.
	uint32_t vendorID;
	uint32_t deviceID;
	uint32_t driverVersion;
	uint32_t driverABI; // Equal to sizeof(void*).
	uint8_t  uuid[VK_UUID_SIZE];

} GFXPipelineCacheHeader_;


/****************************
 * Allocates & builds a hashable key value from a Vk*CreateInfo struct
 * with given replace handles for non-hashable fields.
 * @return Key value, must call free() on success (NULL on failure).
 */
static GFXHashKey_* gfx_cache_alloc_key_(const VkStructureType* createInfo,
                                         const void** handles)
{
	assert(createInfo != NULL);

	// Initialize a hash key builder.
	GFXHashBuilder_ builder;
	if (!gfx_hash_builder_(&builder)) goto error;

	// Based on type, push all the to-be-hashed data.
	// Here we try to minimize the data actually necessary to specify
	// a unique cache object, so everything will be packed tightly.
	// The elements of the Vk*CreateInfo struct will be pushed linearly,
	// such as the specs say, to avoid confusion.
	// Note we do not push any VkStructureType fields except for the main one.
	// Plus we insert the given handles for fields we cannot hash.
	size_t currHandle = 0;
	char temp;

	switch (*createInfo)
	{
	case VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO:

		GFX_KEY_PUSH_(*createInfo);
		const VkDescriptorSetLayoutCreateInfo* dslci =
			(const VkDescriptorSetLayoutCreateInfo*)createInfo;

		// Ignore the pNext field.
		GFX_KEY_PUSH_(dslci->flags);
		GFX_KEY_PUSH_(dslci->bindingCount);

		for (size_t b = 0; b < dslci->bindingCount; ++b)
		{
			const VkDescriptorSetLayoutBinding* dslb = dslci->pBindings + b;
			GFX_KEY_PUSH_(dslb->binding);
			GFX_KEY_PUSH_(dslb->descriptorType);
			GFX_KEY_PUSH_(dslb->descriptorCount);
			GFX_KEY_PUSH_(dslb->stageFlags);

			// Insert bool 'has immutable samplers'.
			temp =
				dslb->descriptorCount > 0 &&
				dslb->pImmutableSamplers != NULL;

			GFX_KEY_PUSH_(temp);

			if (dslb->pImmutableSamplers != NULL)
				for (size_t s = 0; s < dslb->descriptorCount; ++s)
					GFX_KEY_PUSH_HANDLE_();
		}
		break;

	case VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO:

		GFX_KEY_PUSH_(*createInfo);
		const VkPipelineLayoutCreateInfo* plci =
			(const VkPipelineLayoutCreateInfo*)createInfo;

		// Ignore the pNext field.
		// Ignore pipeline layout flags.
		GFX_KEY_PUSH_(plci->setLayoutCount);

		for (size_t s = 0; s < plci->setLayoutCount; ++s)
			GFX_KEY_PUSH_HANDLE_();

		GFX_KEY_PUSH_(plci->pushConstantRangeCount);

		for (size_t p = 0; p < plci->pushConstantRangeCount; ++p)
		{
			GFX_KEY_PUSH_(plci->pPushConstantRanges[p].stageFlags);
			GFX_KEY_PUSH_(plci->pPushConstantRanges[p].offset);
			GFX_KEY_PUSH_(plci->pPushConstantRanges[p].size);
		}
		break;

	case VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO:

		GFX_KEY_PUSH_(*createInfo);
		const VkSamplerCreateInfo* sci =
			(const VkSamplerCreateInfo*)createInfo;

		// Insert bool 'has pNext'.
		temp = sci->pNext != NULL;
		GFX_KEY_PUSH_(temp);

		// Assume pNext is a VkSamplerReductionModeCreateInfo*.
		if (sci->pNext != NULL)
		{
			const VkSamplerReductionModeCreateInfo* srmci =
				(const VkSamplerReductionModeCreateInfo*)sci->pNext;

			// Ignore the pNext field.
			GFX_KEY_PUSH_(srmci->reductionMode);
		}

		// Ignore sampler flags.
		GFX_KEY_PUSH_(sci->magFilter);
		GFX_KEY_PUSH_(sci->minFilter);
		GFX_KEY_PUSH_(sci->mipmapMode);
		GFX_KEY_PUSH_(sci->addressModeU);
		GFX_KEY_PUSH_(sci->addressModeV);
		GFX_KEY_PUSH_(sci->addressModeW);
		GFX_KEY_PUSH_(sci->mipLodBias);
		GFX_KEY_PUSH_(sci->anisotropyEnable);
		GFX_KEY_PUSH_(sci->maxAnisotropy);
		GFX_KEY_PUSH_(sci->compareEnable);
		GFX_KEY_PUSH_(sci->compareOp);
		GFX_KEY_PUSH_(sci->minLod);
		GFX_KEY_PUSH_(sci->maxLod);
		GFX_KEY_PUSH_(sci->borderColor);
		GFX_KEY_PUSH_(sci->unnormalizedCoordinates);
		break;

	case VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO:

		GFX_KEY_PUSH_(*createInfo);
		const VkRenderPassCreateInfo* rpci =
			(const VkRenderPassCreateInfo*)createInfo;

		// Ignore the pNext field.
		// Ignore render pass flags.
		GFX_KEY_PUSH_(rpci->attachmentCount);

		for (size_t a = 0; a < rpci->attachmentCount; ++a)
		{
			GFX_KEY_PUSH_(rpci->pAttachments[a].flags);
			GFX_KEY_PUSH_(rpci->pAttachments[a].format);
			GFX_KEY_PUSH_(rpci->pAttachments[a].samples);
			GFX_KEY_PUSH_(rpci->pAttachments[a].loadOp);
			GFX_KEY_PUSH_(rpci->pAttachments[a].storeOp);
			GFX_KEY_PUSH_(rpci->pAttachments[a].stencilLoadOp);
			GFX_KEY_PUSH_(rpci->pAttachments[a].stencilStoreOp);
			GFX_KEY_PUSH_(rpci->pAttachments[a].initialLayout);
			GFX_KEY_PUSH_(rpci->pAttachments[a].finalLayout);
		}

		GFX_KEY_PUSH_(rpci->subpassCount);

		for (size_t s = 0; s < rpci->subpassCount; ++s)
		{
			const VkSubpassDescription* sd = rpci->pSubpasses + s;
			// Ignore subpass flags.
			// Ignore pipelineBindPoint.
			GFX_KEY_PUSH_(sd->inputAttachmentCount);

			for (size_t i = 0; i < sd->inputAttachmentCount; ++i)
			{
				GFX_KEY_PUSH_(sd->pInputAttachments[i].attachment);
				GFX_KEY_PUSH_(sd->pInputAttachments[i].layout);
			}

			GFX_KEY_PUSH_(sd->colorAttachmentCount);

			for (size_t c = 0; c < sd->colorAttachmentCount; ++c)
			{
				GFX_KEY_PUSH_(sd->pColorAttachments[c].attachment);
				GFX_KEY_PUSH_(sd->pColorAttachments[c].layout);
			}

			// Insert bool 'has resolve attachments'.
			temp =
				sd->colorAttachmentCount > 0 &&
				sd->pResolveAttachments != NULL;

			GFX_KEY_PUSH_(temp);

			if (sd->pResolveAttachments != NULL)
				for (size_t r = 0; r < sd->colorAttachmentCount; ++r)
				{
					GFX_KEY_PUSH_(sd->pResolveAttachments[r].attachment);
					GFX_KEY_PUSH_(sd->pResolveAttachments[r].layout);
				}

			// Insert bool 'has depth stencil attachment'
			temp = sd->pDepthStencilAttachment != NULL;
			GFX_KEY_PUSH_(temp);

			if (sd->pDepthStencilAttachment != NULL)
			{
				GFX_KEY_PUSH_(sd->pDepthStencilAttachment->attachment);
				GFX_KEY_PUSH_(sd->pDepthStencilAttachment->layout);
			}

			GFX_KEY_PUSH_(sd->preserveAttachmentCount);

			for (size_t p = 0; p < sd->preserveAttachmentCount; ++p)
				GFX_KEY_PUSH_(sd->pPreserveAttachments[p]);
		}

		GFX_KEY_PUSH_(rpci->dependencyCount);

		for (size_t d = 0; d < rpci->dependencyCount; ++d)
		{
			GFX_KEY_PUSH_(rpci->pDependencies[d].srcSubpass);
			GFX_KEY_PUSH_(rpci->pDependencies[d].dstSubpass);
			GFX_KEY_PUSH_(rpci->pDependencies[d].srcStageMask);
			GFX_KEY_PUSH_(rpci->pDependencies[d].dstStageMask);
			GFX_KEY_PUSH_(rpci->pDependencies[d].srcAccessMask);
			GFX_KEY_PUSH_(rpci->pDependencies[d].dstAccessMask);
			GFX_KEY_PUSH_(rpci->pDependencies[d].dependencyFlags);
		}
		break;

	case VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO:

		GFX_KEY_PUSH_(*createInfo);
		const VkGraphicsPipelineCreateInfo* gpci =
			(const VkGraphicsPipelineCreateInfo*)createInfo;

		// Ignore the pNext field.
		GFX_KEY_PUSH_(gpci->flags);
		GFX_KEY_PUSH_(gpci->stageCount);

		for (size_t s = 0; s < gpci->stageCount; ++s)
		{
			const VkPipelineShaderStageCreateInfo* pssci = gpci->pStages + s;
			// Ignore the pNext field.
			// Ignore shader stage flags.
			GFX_KEY_PUSH_(pssci->stage);
			GFX_KEY_PUSH_HANDLE_();
			// Ignore the entry point name.

			// Insert bool 'has specialization info'.
			temp = pssci->pSpecializationInfo != NULL;
			GFX_KEY_PUSH_(temp);

			if (pssci->pSpecializationInfo != NULL)
			{
				const VkSpecializationInfo* si = pssci->pSpecializationInfo;
				GFX_KEY_PUSH_(si->mapEntryCount);

				for (size_t e = 0; e < si->mapEntryCount; ++e)
				{
					GFX_KEY_PUSH_(si->pMapEntries[e].constantID);
					// Ignore the offset field.
					GFX_KEY_PUSH_(si->pMapEntries[e].size);

					if (!gfx_hash_builder_push_(
						&builder, si->pMapEntries[e].size,
						(char*)si->pData + si->pMapEntries[e].offset))
					{
						goto clean;
					}
				}

				// Ignore the dataSize field.
				// pData field implicitly pushed above.
			}
		}

		const VkPipelineVertexInputStateCreateInfo* pvisci = gpci->pVertexInputState;
		// Ignore the pNext field.
		// Ignore vertex input state flags.
		GFX_KEY_PUSH_(pvisci->vertexBindingDescriptionCount);

		for (size_t b = 0; b < pvisci->vertexBindingDescriptionCount; ++b)
		{
			const VkVertexInputBindingDescription* vibd =
				pvisci->pVertexBindingDescriptions + b;

			GFX_KEY_PUSH_(vibd->binding);
			GFX_KEY_PUSH_(vibd->stride);
			GFX_KEY_PUSH_(vibd->inputRate);
		}

		GFX_KEY_PUSH_(pvisci->vertexAttributeDescriptionCount);

		for (size_t a = 0; a < pvisci->vertexAttributeDescriptionCount; ++a)
		{
			const VkVertexInputAttributeDescription* viad =
				pvisci->pVertexAttributeDescriptions + a;

			GFX_KEY_PUSH_(viad->location);
			GFX_KEY_PUSH_(viad->binding);
			GFX_KEY_PUSH_(viad->format);
			GFX_KEY_PUSH_(viad->offset);
		}

		const VkPipelineInputAssemblyStateCreateInfo* piasci = gpci->pInputAssemblyState;
		// Ignore the pNext field.
		// Ignore input assembly state flags.
		GFX_KEY_PUSH_(piasci->topology);
		GFX_KEY_PUSH_(piasci->primitiveRestartEnable);

		// Insert bool 'has tessellation state'.
		temp = gpci->pTessellationState != NULL;
		GFX_KEY_PUSH_(temp);

		if (gpci->pTessellationState != NULL)
		{
			const VkPipelineTessellationStateCreateInfo* ptsci = gpci->pTessellationState;
			// Ignore the pNext field.
			// Ignore tessellation state flags.
			GFX_KEY_PUSH_(ptsci->patchControlPoints);
		}

		// Insert bool 'has viewport state'.
		temp = gpci->pViewportState != NULL;
		GFX_KEY_PUSH_(temp);

		if (gpci->pViewportState != NULL)
		{
			const VkPipelineViewportStateCreateInfo* pvsci = gpci->pViewportState;
			// Ignore the pNext field.
			// Ignore viewport state flags.
			GFX_KEY_PUSH_(pvsci->viewportCount);

			// Insert bool 'has viewports'.
			temp =
				pvsci->viewportCount > 0 &&
				pvsci->pViewports != NULL;

			GFX_KEY_PUSH_(temp);

			if (pvsci->pViewports != NULL)
				for (size_t v = 0; v < pvsci->viewportCount; ++v)
				{
					GFX_KEY_PUSH_(pvsci->pViewports[v].x);
					GFX_KEY_PUSH_(pvsci->pViewports[v].y);
					GFX_KEY_PUSH_(pvsci->pViewports[v].width);
					GFX_KEY_PUSH_(pvsci->pViewports[v].height);
					GFX_KEY_PUSH_(pvsci->pViewports[v].minDepth);
					GFX_KEY_PUSH_(pvsci->pViewports[v].maxDepth);
				}

			GFX_KEY_PUSH_(pvsci->scissorCount);

			// Insert bool 'has scissors'.
			temp =
				pvsci->scissorCount > 0 &&
				pvsci->pScissors != NULL;

			GFX_KEY_PUSH_(temp);

			if (pvsci->pScissors != NULL)
				for (size_t s = 0; s < pvsci->scissorCount; ++s)
				{
					GFX_KEY_PUSH_(pvsci->pScissors[s].offset);
					GFX_KEY_PUSH_(pvsci->pScissors[s].extent);
				}
		}

		const VkPipelineRasterizationStateCreateInfo* prsci = gpci->pRasterizationState;
		// Ignore the pNext field.
		// Ignore rasterization state flags.
		GFX_KEY_PUSH_(prsci->depthClampEnable);
		GFX_KEY_PUSH_(prsci->rasterizerDiscardEnable);
		GFX_KEY_PUSH_(prsci->polygonMode);
		GFX_KEY_PUSH_(prsci->cullMode);
		GFX_KEY_PUSH_(prsci->frontFace);
		GFX_KEY_PUSH_(prsci->depthBiasEnable);
		GFX_KEY_PUSH_(prsci->depthBiasConstantFactor);
		GFX_KEY_PUSH_(prsci->depthBiasClamp);
		GFX_KEY_PUSH_(prsci->depthBiasSlopeFactor);
		GFX_KEY_PUSH_(prsci->lineWidth);

		// Insert bool 'has multisample state'.
		temp = gpci->pMultisampleState != NULL;
		GFX_KEY_PUSH_(temp);

		if (gpci->pMultisampleState != NULL)
		{
			const VkPipelineMultisampleStateCreateInfo* pmsci = gpci->pMultisampleState;
			// Ignore the pNext field.
			// Ignore multisample state flags.
			GFX_KEY_PUSH_(pmsci->rasterizationSamples);
			GFX_KEY_PUSH_(pmsci->sampleShadingEnable);
			GFX_KEY_PUSH_(pmsci->minSampleShading);
			// Ignore sample masks.
			GFX_KEY_PUSH_(pmsci->alphaToCoverageEnable);
			GFX_KEY_PUSH_(pmsci->alphaToOneEnable);
		}

		// Insert bool 'has depth stencil state'.
		temp = gpci->pDepthStencilState != NULL;
		GFX_KEY_PUSH_(temp);

		if (gpci->pDepthStencilState != NULL)
		{
			const VkPipelineDepthStencilStateCreateInfo* pdssci = gpci->pDepthStencilState;
			// Ignore the pNext field.
			// Ignore depth stencil state flags.
			GFX_KEY_PUSH_(pdssci->depthTestEnable);
			GFX_KEY_PUSH_(pdssci->depthWriteEnable);
			GFX_KEY_PUSH_(pdssci->depthCompareOp);
			GFX_KEY_PUSH_(pdssci->depthBoundsTestEnable);
			GFX_KEY_PUSH_(pdssci->stencilTestEnable);
			GFX_KEY_PUSH_(pdssci->front.failOp);
			GFX_KEY_PUSH_(pdssci->front.passOp);
			GFX_KEY_PUSH_(pdssci->front.depthFailOp);
			GFX_KEY_PUSH_(pdssci->front.compareOp);
			GFX_KEY_PUSH_(pdssci->front.compareMask);
			GFX_KEY_PUSH_(pdssci->front.writeMask);
			GFX_KEY_PUSH_(pdssci->front.reference);
			GFX_KEY_PUSH_(pdssci->back.failOp);
			GFX_KEY_PUSH_(pdssci->back.passOp);
			GFX_KEY_PUSH_(pdssci->back.depthFailOp);
			GFX_KEY_PUSH_(pdssci->back.compareOp);
			GFX_KEY_PUSH_(pdssci->back.compareMask);
			GFX_KEY_PUSH_(pdssci->back.writeMask);
			GFX_KEY_PUSH_(pdssci->back.reference);
			GFX_KEY_PUSH_(pdssci->minDepthBounds);
			GFX_KEY_PUSH_(pdssci->maxDepthBounds);
		}

		// Insert bool 'has color blend state'.
		temp = gpci->pColorBlendState != NULL;
		GFX_KEY_PUSH_(temp);

		if (gpci->pColorBlendState != NULL)
		{
			const VkPipelineColorBlendStateCreateInfo* pcbsci = gpci->pColorBlendState;
			// Ignore the pNext field.
			// Ignore color blend state flags.
			GFX_KEY_PUSH_(pcbsci->logicOpEnable);
			GFX_KEY_PUSH_(pcbsci->logicOp);
			GFX_KEY_PUSH_(pcbsci->attachmentCount);

			for (size_t a = 0; a < pcbsci->attachmentCount; ++a)
			{
				GFX_KEY_PUSH_(pcbsci->pAttachments[a].blendEnable);
				GFX_KEY_PUSH_(pcbsci->pAttachments[a].srcColorBlendFactor);
				GFX_KEY_PUSH_(pcbsci->pAttachments[a].dstColorBlendFactor);
				GFX_KEY_PUSH_(pcbsci->pAttachments[a].colorBlendOp);
				GFX_KEY_PUSH_(pcbsci->pAttachments[a].srcAlphaBlendFactor);
				GFX_KEY_PUSH_(pcbsci->pAttachments[a].dstAlphaBlendFactor);
				GFX_KEY_PUSH_(pcbsci->pAttachments[a].alphaBlendOp);
				GFX_KEY_PUSH_(pcbsci->pAttachments[a].colorWriteMask);
			}

			if (!gfx_hash_builder_push_(
				&builder, sizeof(pcbsci->blendConstants), pcbsci->blendConstants))
			{
				goto clean;
			}
		}

		// Insert bool 'has dynamic state'.
		temp = gpci->pDynamicState != NULL;
		GFX_KEY_PUSH_(temp);

		if (gpci->pDynamicState != NULL)
		{
			const VkPipelineDynamicStateCreateInfo* pdsci = gpci->pDynamicState;
			// Ignore the pNext field.
			// Ignore dynamic state flags.
			GFX_KEY_PUSH_(pdsci->dynamicStateCount);

			for (size_t d = 0; d < pdsci->dynamicStateCount; ++d)
				GFX_KEY_PUSH_(pdsci->pDynamicStates[d]);
		}

		GFX_KEY_PUSH_HANDLE_();
		GFX_KEY_PUSH_HANDLE_();
		GFX_KEY_PUSH_(gpci->subpass);
		// Ignore base pipeline.
		// Ignore pipeline index.
		break;

	case VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO:

		GFX_KEY_PUSH_(*createInfo);
		const VkComputePipelineCreateInfo* cpci =
			(const VkComputePipelineCreateInfo*)createInfo;

		// Ignore the pNext field.
		GFX_KEY_PUSH_(cpci->flags);
		// Ignore the pNext field.
		// Ignore shader stage flags.
		GFX_KEY_PUSH_(cpci->stage.stage);
		GFX_KEY_PUSH_HANDLE_();
		// Ignore the entry point name.

		// Insert bool 'has specialization info'.
		temp = cpci->stage.pSpecializationInfo != NULL;
		GFX_KEY_PUSH_(temp);

		if (cpci->stage.pSpecializationInfo != NULL)
		{
			const VkSpecializationInfo* si = cpci->stage.pSpecializationInfo;
			GFX_KEY_PUSH_(si->mapEntryCount);

			for (size_t e = 0; e < si->mapEntryCount; ++e)
			{
				GFX_KEY_PUSH_(si->pMapEntries[e].constantID);
				// Ignore the offset field.
				GFX_KEY_PUSH_(si->pMapEntries[e].size);

				if (!gfx_hash_builder_push_(
					&builder, si->pMapEntries[e].size,
					(char*)si->pData + si->pMapEntries[e].offset))
				{
					goto clean;
				}
			}

			// Ignore the dataSize field.
			// pData field implicitly pushed above.
		}

		GFX_KEY_PUSH_HANDLE_();
		// Ignore base pipeline.
		// Ignore pipeline index.
		break;

	default:
		goto clean;
	}

	// Return the key data.
	return gfx_hash_builder_get_(&builder);


	// Cleanup on failure.
clean:
	free(gfx_hash_builder_get_(&builder));
error:
	gfx_log_error("Could not allocate key for cached Vulkan object.");

	return NULL;
}

/****************************
 * Creates a new Vulkan object using the given Vk*CreateInfo struct and
 * outputs to the given GFXCacheElem_ struct.
 * @return Non-zero on success.
 */
static bool gfx_cache_create_elem_(GFXCache_* cache, GFXCacheElem_* elem,
                                   const VkStructureType* createInfo)
{
	assert(cache != NULL);
	assert(elem != NULL);
	assert(createInfo != NULL);

	GFXContext_* context = cache->context;

	// Firstly, set type.
	elem->type = *createInfo;

	// Then call the appropriate create function.
	switch (elem->type)
	{
	case VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO:
		GFX_VK_CHECK_(
			context->vk.CreateDescriptorSetLayout(context->vk.device,
				(const VkDescriptorSetLayoutCreateInfo*)createInfo, NULL,
				&elem->vk.setLayout),
			goto error);

		// Go ahead and just create an update template inline.
		// This is as simple as creating an update entry for each binding.
		// We always update descriptor sets as a whole.
		{
			const VkDescriptorSetLayoutCreateInfo* dslci =
				(const VkDescriptorSetLayoutCreateInfo*)createInfo;

			VkDescriptorUpdateTemplateEntry entries[dslci->bindingCount];
			uint32_t count = dslci->bindingCount;
			size_t offset = 0;

			for (uint32_t b = 0; b < dslci->bindingCount; ++b)
			{
				if (
					dslci->pBindings[b].descriptorCount == 0 ||
					(dslci->pBindings[b].pImmutableSamplers != NULL &&
					dslci->pBindings[b].descriptorType == VK_DESCRIPTOR_TYPE_SAMPLER))
				{
					// Skip empty bindings or immutable samplers.
					--count;
					continue;
				}

				// Entry index.
				uint32_t e = b - (dslci->bindingCount - count);

				entries[e] = (VkDescriptorUpdateTemplateEntry){
					.dstBinding      = dslci->pBindings[b].binding,
					.dstArrayElement = 0,
					.descriptorCount = dslci->pBindings[b].descriptorCount,
					.descriptorType  = dslci->pBindings[b].descriptorType,
					.offset          = offset,
					.stride          = cache->templateStride
				};
				offset +=
					cache->templateStride *
					entries[e].descriptorCount;
			}

			// If no bindings remain, do not create an update template!
			if (count == 0)
			{
				elem->vk.template = VK_NULL_HANDLE;
				break;
			}

			VkDescriptorUpdateTemplateCreateInfo dutci = {
				.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO,

				.pNext                      = NULL,
				.flags                      = 0,
				.descriptorUpdateEntryCount = count,
				.pDescriptorUpdateEntries   = entries,
				.descriptorSetLayout        = elem->vk.setLayout,

				.templateType = VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_DESCRIPTOR_SET
			};

			GFX_VK_CHECK_(
				context->vk.CreateDescriptorUpdateTemplate(
					context->vk.device, &dutci, NULL, &elem->vk.template),
				{
					context->vk.DestroyDescriptorSetLayout(
						context->vk.device, elem->vk.setLayout, NULL);
					goto error;
				});
		}
		break;

	case VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO:
		GFX_VK_CHECK_(
			context->vk.CreatePipelineLayout(context->vk.device,
				(const VkPipelineLayoutCreateInfo*)createInfo, NULL,
				&elem->vk.layout),
			goto error);
		break;

	case VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO:
		// For samplers we have to check against Vulkan's allocation limit.
		// We have to lock such that two concurrent allocations both fail
		// properly if the limit only allows one more sampler.
		gfx_mutex_lock_(&context->limits.samplerLock);

		if (atomic_load(&context->limits.samplers) >= context->limits.maxSamplers)
		{
			gfx_log_error(
				"Cannot allocate sampler because physical device limit "
				"of %"PRIu32" sampler allocations has been reached.",
				context->limits.maxSamplers);

			gfx_mutex_unlock_(&context->limits.samplerLock);
			goto error;
		}

		// Increase the count & unlock.
		// Just unlock early, just like with memory allocations.
		atomic_fetch_add(&context->limits.samplers, 1);

		gfx_mutex_unlock_(&context->limits.samplerLock);

		GFX_VK_CHECK_(
			context->vk.CreateSampler(context->vk.device,
				(const VkSamplerCreateInfo*)createInfo, NULL,
				&elem->vk.sampler),
			{
				// Undo...
				atomic_fetch_sub(&context->limits.samplers, 1);
				goto error;
			});
		break;

	case VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO:
		GFX_VK_CHECK_(
			context->vk.CreateRenderPass(context->vk.device,
				(const VkRenderPassCreateInfo*)createInfo, NULL,
				&elem->vk.pass),
			goto error);
		break;

	case VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO:
		GFX_VK_CHECK_(
			context->vk.CreateGraphicsPipelines(context->vk.device,
				cache->vk.cache, 1,
				(const VkGraphicsPipelineCreateInfo*)createInfo, NULL,
				&elem->vk.pipeline),
			goto error);
		break;

	case VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO:
		GFX_VK_CHECK_(
			context->vk.CreateComputePipelines(context->vk.device,
				cache->vk.cache, 1,
				(const VkComputePipelineCreateInfo*)createInfo, NULL,
				&elem->vk.pipeline),
			goto error);
		break;

	default:
		goto error;
	}

	return 1;


	// Error on failure.
error:
	gfx_log_error("Could not create cached Vulkan object.");
	return 0;
}

/****************************
 * Destroys the Vulkan object stored in the given GFXCacheElem_ struct.
 */
static void gfx_cache_destroy_elem_(GFXCache_* cache, GFXCacheElem_* elem)
{
	assert(cache != NULL);
	assert(elem != NULL);

	GFXContext_* context = cache->context;

	// Call the appropriate destroy function from type.
	switch (elem->type)
	{
	case VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO:
		context->vk.DestroyDescriptorUpdateTemplate(
			context->vk.device, elem->vk.template, NULL);
		context->vk.DestroyDescriptorSetLayout(
			context->vk.device, elem->vk.setLayout, NULL);
		break;

	case VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO:
		context->vk.DestroyPipelineLayout(
			context->vk.device, elem->vk.layout, NULL);
		break;

	case VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO:
		// We actually do decrease the sampler allocation count afterwards.
		context->vk.DestroySampler(
			context->vk.device, elem->vk.sampler, NULL);

		atomic_fetch_sub(&context->limits.samplers, 1);
		break;

	case VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO:
		context->vk.DestroyRenderPass(
			context->vk.device, elem->vk.pass, NULL);
		break;

	case VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO:
	case VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO:
		context->vk.DestroyPipeline(
			context->vk.device, elem->vk.pipeline, NULL);
		break;

	default:
		break;
	}
}

/****************************
 * Stand-in function for gfx_cache_get_ when given anything other than
 * a Vk*PipelineCreateInfo struct, i.e. we use the simple cache.
 */
static GFXCacheElem_* gfx_cache_get_simple_(GFXCache_* cache,
                                            const VkStructureType* createInfo,
                                            const void** handles)
{
	assert(cache != NULL);
	assert(createInfo != NULL);
	assert(
		*createInfo != VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO &&
		*createInfo != VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO);

	// Firstly we create a key value & hash it.
	GFXHashKey_* key = gfx_cache_alloc_key_(createInfo, handles);
	if (key == NULL) return NULL;

	const uint64_t hash = cache->simple.hash(key);

	// Here we do need to lock the simple cache, as we want the function
	// to be reentrant. And we have a dedicated lock!
	gfx_mutex_lock_(&cache->simpleLock);

	// Try to find a matching element first.
	GFXCacheElem_* elem = gfx_map_hsearch(&cache->simple, key, hash);
	if (elem == NULL)
	{
		// If not found, create and insert a new element.
		elem = gfx_map_hinsert(
			&cache->simple, NULL, gfx_hash_size_(key), key, hash);

		if (elem != NULL && !gfx_cache_create_elem_(cache, elem, createInfo))
		{
			// On failure, erase & set return to NULL.
			gfx_map_erase(&cache->simple, elem);
			elem = NULL;
		}
	}

	// Unlock, free data & return.
	gfx_mutex_unlock_(&cache->simpleLock);
	free(key);
	return elem;
}

/****************************
 * Stand-in function for gfx_cache_get_ when given
 * a Vk*PipelineCreateInfo struct.
 */
static GFXCacheElem_* gfx_cache_get_pipeline_(GFXCache_* cache,
                                              const VkStructureType* createInfo,
                                              const void** handles)
{
	assert(cache != NULL);
	assert(createInfo != NULL);
	assert(
		*createInfo == VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO ||
		*createInfo == VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO);

	// Again, create a key value & hash it.
	GFXHashKey_* key = gfx_cache_alloc_key_(createInfo, handles);
	if (key == NULL) return NULL;

	const uint64_t hash = cache->immutable.hash(key);

	// First we check the immutable cache.
	// This function does not need to run concurrent with gfx_cache_warmup_
	// and we do not modify, therefore we do not lock this cache :)
	GFXCacheElem_* elem = gfx_map_hsearch(&cache->immutable, key, hash);
	if (elem != NULL) goto found;

	// If not found in the immutable cache, check the mutable cache.
	// For this lookup we obviously do lock.
	gfx_mutex_lock_(&cache->lookupLock);
	elem = gfx_map_hsearch(&cache->mutable, key, hash);
	gfx_mutex_unlock_(&cache->lookupLock);

	if (elem != NULL) goto found;

	// If we did not find it yet, we need to insert a new element in the
	// mutable cache. We want other threads to still be able to query while
	// creating, so we lock for 'creation' separately.
	// But then we need to immediately check if the element already exists.
	// This because multiple threads could simultaneously decide to create
	// the same new element.
	gfx_mutex_lock_(&cache->createLock);

	gfx_mutex_lock_(&cache->lookupLock);
	elem = gfx_map_hsearch(&cache->mutable, key, hash);
	gfx_mutex_unlock_(&cache->lookupLock);

	if (elem != NULL)
	{
		gfx_mutex_unlock_(&cache->createLock);
		goto found;
	}

	// At this point we are the thread to actually create the new element.
	// We first create, then insert, so other threads don't accidentally
	// pick an incomplete element.
	GFXCacheElem_ newElem;
	if (!gfx_cache_create_elem_(cache, &newElem, createInfo))
	{
		// Uh oh failed to create :(
		gfx_mutex_unlock_(&cache->createLock);
		free(key);
		return NULL;
	}

	// We created the thing, now insert the thing.
	// For this we block any lookups again.
	// When we're done we can also unlock for creation tho :)
	gfx_mutex_lock_(&cache->lookupLock);

	elem = gfx_map_hinsert(
		&cache->mutable, &newElem, gfx_hash_size_(key), key, hash);

	gfx_mutex_unlock_(&cache->lookupLock);
	gfx_mutex_unlock_(&cache->createLock);

	if (elem != NULL) goto found;

	// Ah, well, it is not in the map, away with it then...
	gfx_cache_destroy_elem_(cache, &newElem);
	free(key);
	return NULL;


	// Free data & return when found.
found:
	free(key);
	return elem;
}

/****************************/
bool gfx_cache_init_(GFXCache_* cache, GFXDevice_* device, size_t templateStride)
{
	assert(cache != NULL);
	assert(device != NULL);
	assert(device->context != NULL);
	assert(templateStride > 0);

	GFXContext_* context = device->context;

	cache->context = context;
	cache->templateStride = templateStride;
	cache->vk.device = device->vk.device;

	// Initialize the locks.
	if (!gfx_mutex_init_(&cache->simpleLock))
		return 0;

	if (!gfx_mutex_init_(&cache->lookupLock))
		goto clean_simple;

	if (!gfx_mutex_init_(&cache->createLock))
		goto clean_lookup;

	// Create an empty pipeline cache.
	VkPipelineCacheCreateInfo pcci = {
		.sType = VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO,

		.pNext           = NULL,
		.flags           = 0,
		.initialDataSize = 0,
		.pInitialData    = NULL
	};

	GFX_VK_CHECK_(context->vk.CreatePipelineCache(
		context->vk.device, &pcci, NULL, &cache->vk.cache), goto clean);

	// Initialize the hashtables.
	gfx_map_init(&cache->simple,
		sizeof(GFXCacheElem_), gfx_hash_murmur3_, gfx_hash_cmp_);
	gfx_map_init(&cache->immutable,
		sizeof(GFXCacheElem_), gfx_hash_murmur3_, gfx_hash_cmp_);
	gfx_map_init(&cache->mutable,
		sizeof(GFXCacheElem_), gfx_hash_murmur3_, gfx_hash_cmp_);

	return 1;


	// Cleanup on failure.
clean:
	gfx_mutex_clear_(&cache->createLock);
clean_lookup:
	gfx_mutex_clear_(&cache->lookupLock);
clean_simple:
	gfx_mutex_clear_(&cache->simpleLock);

	return 0;
}

/****************************/
void gfx_cache_clear_(GFXCache_* cache)
{
	assert(cache != NULL);

	GFXContext_* context = cache->context;

	// Destroy all objects in the mutable cache.
	for (
		GFXCacheElem_* elem = gfx_map_first(&cache->mutable);
		elem != NULL;
		elem = gfx_map_next(&cache->mutable, elem))
	{
		gfx_cache_destroy_elem_(cache, elem);
	}

	// Destroy all objects in the immutable cache.
	for (
		GFXCacheElem_* elem = gfx_map_first(&cache->immutable);
		elem != NULL;
		elem = gfx_map_next(&cache->immutable, elem))
	{
		gfx_cache_destroy_elem_(cache, elem);
	}

	// Destroy all objects in the simple cache.
	for (
		GFXCacheElem_* elem = gfx_map_first(&cache->simple);
		elem != NULL;
		elem = gfx_map_next(&cache->simple, elem))
	{
		gfx_cache_destroy_elem_(cache, elem);
	}

	// Destroy the pipeline cache.
	context->vk.DestroyPipelineCache(
		context->vk.device, cache->vk.cache, NULL);

	// Clear all other things.
	gfx_map_clear(&cache->simple);
	gfx_map_clear(&cache->immutable);
	gfx_map_clear(&cache->mutable);

	gfx_mutex_clear_(&cache->simpleLock);
	gfx_mutex_clear_(&cache->lookupLock);
	gfx_mutex_clear_(&cache->createLock);
}

/****************************/
bool gfx_cache_flush_(GFXCache_* cache)
{
	assert(cache != NULL);

	// No need to lock anything, we just merge the tables.
	return gfx_map_merge(&cache->immutable, &cache->mutable);
}

/****************************/
GFXCacheElem_* gfx_cache_get_(GFXCache_* cache,
                              const VkStructureType* createInfo,
                              const void** handles)
{
	assert(cache != NULL);
	assert(createInfo != NULL);

	// Just route to the correct cache.
	const bool isPipeline =
		*createInfo == VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO ||
		*createInfo == VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;

	if (isPipeline)
		return gfx_cache_get_pipeline_(cache, createInfo, handles);
	else
		return gfx_cache_get_simple_(cache, createInfo, handles);
}

/****************************/
bool gfx_cache_warmup_(GFXCache_* cache,
                       const VkStructureType* createInfo,
                       const void** handles)
{
	assert(cache != NULL);
	assert(createInfo != NULL);
	assert(
		*createInfo == VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO ||
		*createInfo == VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO);

	// Create a key value & hash it.
	GFXHashKey_* key = gfx_cache_alloc_key_(createInfo, handles);
	if (key == NULL) return 0;

	const uint64_t hash = cache->immutable.hash(key);

	// Here we do need to lock the immutable cache, as we want the function
	// to be reentrant. However we have no dedicated lock.
	// Luckily this function _does not_ need to be able to run concurrently
	// with gfx_cache_get_pipeline_, so we abuse the lookup lock :)
	gfx_mutex_lock_(&cache->lookupLock);

	// Try to find a matching element first.
	GFXCacheElem_* elem = gfx_map_hsearch(&cache->immutable, key, hash);
	if (elem != NULL)
		// Found one, done, we do not care if it is completely built yet.
		gfx_mutex_unlock_(&cache->lookupLock);
	else
	{
		// If not found, insert a new element.
		// Then immediately unlock so other warmups can be performed.
		elem = gfx_map_hinsert(
			&cache->immutable, NULL, gfx_hash_size_(key), key, hash);

		gfx_mutex_unlock_(&cache->lookupLock);

		// THEN create it :)
		if (elem == NULL || !gfx_cache_create_elem_(cache, elem, createInfo))
		{
			// Failed.. I suppose we erase the element.
			if (elem != NULL)
			{
				gfx_mutex_lock_(&cache->lookupLock);
				gfx_map_erase(&cache->immutable, elem);
				gfx_mutex_unlock_(&cache->lookupLock);
			}

			free(key);
			return 0;
		}
	}

	// Free data & return.
	free(key);
	return 1;
}

/****************************/
bool gfx_cache_load_(GFXCache_* cache, const GFXReader* src)
{
	assert(groufix_.vk.instance != NULL);
	assert(cache != NULL);
	assert(src != NULL);

	GFXContext_* context = cache->context;

	// We use a hash key builder for pipeline caches too :o
	GFXHashBuilder_ builder;
	if (!gfx_hash_builder_(&builder)) return 0;

	// Then stick empty data in it big enough for the source.
	long long len = gfx_io_len(src);
	if (len <= 0) goto clean_builder;

	void* bData = gfx_hash_builder_push_(&builder, (size_t)len, NULL);
	if (bData == NULL) goto clean_builder;

	// Read cache data.
	len = gfx_io_read(src, bData, (size_t)len);
	if (len <= 0) goto clean_builder;

	// Claim builder data & unpack the groufix header.
	GFXHashKey_* key = gfx_hash_builder_get_(&builder);
	key->len = (size_t)len; // In case of shorter read.

	GFXPipelineCacheHeader_ header;
	const size_t headerSize =
		sizeof(header.magic) + sizeof(header.dataSize) +
		sizeof(header.dataHash) + sizeof(header.vendorID) +
		sizeof(header.deviceID) + sizeof(header.driverVersion) +
		sizeof(header.driverABI) + sizeof(header.uuid);

	// What's this, not even a header >:(
	if (key->len < headerSize)
	{
		gfx_log_error(
			"Could not load pipeline cache; "
			"groufix header is incomplete.");

		free(key);
		return 0;
	}

	const uint64_t emptyHash = 0;
	char* head = key->bytes;

	memcpy(&header.magic, head, sizeof(header.magic));
	head += sizeof(header.magic);
	memcpy(&header.dataSize, head, sizeof(header.dataSize));
	head += sizeof(header.dataSize);
	memcpy(&header.dataHash, head, sizeof(header.dataHash));
	// Set dataHash to 0 in the received data so we can hash & compare it :)
	memcpy(head, &emptyHash, sizeof(header.dataHash));
	head += sizeof(header.dataHash);
	memcpy(&header.vendorID, head, sizeof(header.vendorID));
	head += sizeof(header.vendorID);
	memcpy(&header.deviceID, head, sizeof(header.deviceID));
	head += sizeof(header.deviceID);
	memcpy(&header.driverVersion, head, sizeof(header.driverVersion));
	head += sizeof(header.driverVersion);
	memcpy(&header.driverABI, head, sizeof(header.driverABI));
	head += sizeof(header.driverABI);
	memcpy(header.uuid, head, sizeof(header.uuid));
	head += sizeof(header.uuid);

	// Validate the received data.
	{
		// Get allocation limit in a scope so pdp gets freed :)
		VkPhysicalDeviceProperties pdp;
		groufix_.vk.GetPhysicalDeviceProperties(cache->vk.device, &pdp);

		if (
			header.magic != GFX_HEADER_MAGIC_ ||
			header.dataSize != key->len ||
			header.dataHash != gfx_hash_murmur3_(key) ||
			header.vendorID != pdp.vendorID ||
			header.deviceID != pdp.deviceID ||
			header.driverVersion != pdp.driverVersion ||
			header.driverABI != (uint32_t)sizeof(void*) ||
			memcmp(header.uuid, pdp.pipelineCacheUUID, sizeof(header.uuid)) != 0)
		{
			gfx_log_error(
				"Could not load pipeline cache; "
				"data is invalid or incompatible.");

			free(key);
			return 0;
		}
	}

	// Create a temporary Vulkan pipeline cache.
	VkPipelineCacheCreateInfo pcci = {
		.sType = VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO,

		.pNext           = NULL,
		.flags           = 0,
		.initialDataSize = key->len - headerSize,
		.pInitialData    = head
	};

	VkPipelineCache vkCache;
	GFX_VK_CHECK_(
		context->vk.CreatePipelineCache(
			context->vk.device, &pcci, NULL, &vkCache),
		{
			gfx_log_error("Failed to load pipeline cache.");

			free(key);
			return 0;
		});

	// And finally, merge the temporary pipeline & destroy it.
	bool success = 1;

	GFX_VK_CHECK_(
		context->vk.MergePipelineCaches(
			context->vk.device, cache->vk.cache, 1, &vkCache),
		{
			gfx_log_error("Failed to merge pipeline cache.");
			success = 0;
		});

	context->vk.DestroyPipelineCache(
		context->vk.device, vkCache, NULL);

	// Some victory logs c:
	if (success)
		gfx_log_info(
			"Successfully loaded groufix pipeline cache:\n"
			"    Input size: %"GFX_PRIs" bytes.\n",
			key->len);

	free(key);
	return success;


	// Cleanup the builder on failure.
clean_builder:
	gfx_log_error("Could not read pipeline cache from stream.");

	free(gfx_hash_builder_get_(&builder));
	return 0;
}

/****************************/
bool gfx_cache_store_(GFXCache_* cache, const GFXWriter* dst)
{
	assert(groufix_.vk.instance != NULL);
	assert(cache != NULL);
	assert(dst != NULL);

	GFXContext_* context = cache->context;

	// Again with the hash key builder c:
	GFXHashBuilder_ builder;
	if (!gfx_hash_builder_(&builder)) return 0;

	// Create & push a groufix header, needs to be packed!
	// Given this function follows the same makeup as gfx_cache_alloc_key_,
	// we are very much going to abuse the GFX_KEY_PUSH_ macro.
	const uint32_t magic = GFX_HEADER_MAGIC_;
	const uint32_t emptySize = 0;
	const uint64_t emptyHash = 0;
	const uint32_t driverABI = (uint32_t)sizeof(void*);

	GFX_KEY_PUSH_(magic);
	GFX_KEY_PUSH_(emptySize);
	GFX_KEY_PUSH_(emptyHash);

	{
		// Get allocation limit in a scope so pdp gets freed :)
		VkPhysicalDeviceProperties pdp;
		groufix_.vk.GetPhysicalDeviceProperties(cache->vk.device, &pdp);

		GFX_KEY_PUSH_(pdp.vendorID);
		GFX_KEY_PUSH_(pdp.deviceID);
		GFX_KEY_PUSH_(pdp.driverVersion);
		GFX_KEY_PUSH_(driverABI);

		if (!gfx_hash_builder_push_(
			&builder, sizeof(pdp.pipelineCacheUUID), pdp.pipelineCacheUUID))
		{
			goto clean;
		}
	}

	// Get the size of the pipeline cache.
	// Then push a big enough chunk for the cache data & get the data.
	size_t vkSize;
	GFX_VK_CHECK_(context->vk.GetPipelineCacheData(
		context->vk.device, cache->vk.cache, &vkSize, NULL), goto clean);

	void* bData = gfx_hash_builder_push_(&builder, vkSize, NULL);
	if (bData == NULL) goto clean;

	GFX_VK_CHECK_(context->vk.GetPipelineCacheData(
		context->vk.device, cache->vk.cache, &vkSize, bData), goto clean);

	// Claim builder data.
	// Set its `dataSize` so we can hash.
	GFXHashKey_* key = gfx_hash_builder_get_(&builder);
	memcpy(
		(uint32_t*)key->bytes + 1, // Right after `magic`.
		&key->len,
		sizeof(uint32_t));

	// Then hash while `dataHash` is 0 and set it afterwards
	const uint64_t hash = gfx_hash_murmur3_(key);
	memcpy(
		(uint32_t*)key->bytes + 2, // Right after `dataSize`.
		&hash,
		sizeof(uint64_t));

	// Stream out the data.
	if (gfx_io_write(dst, key->bytes, key->len) <= 0)
	{
		gfx_log_error("Could not write pipeline cache to stream.");
		free(key);
		return 0;
	}

	// Yey we did it!
	gfx_log_info(
		"Written groufix pipeline cache to stream (%"GFX_PRIs" bytes).",
		key->len);

	free(key);
	return 1;


	// Cleanup on failure.
clean:
	gfx_log_error("Failed to store pipeline cache.");

	free(gfx_hash_builder_get_(&builder));
	return 0;
}
